# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, Qt
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        MainWindow.setStyleSheet("background-color: rgb(67, 40, 24);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(90, 260, 130, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
                                            "    border-radius: 15px;\n"
                                            "    background-color: rgb(255, 230, 167);\n"
                                            "    color: rgb(67, 40, 24);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    border-radius: 15px;\n"
                                            "    background-color: rgb(187, 148, 87);\n"
                                            "    color: rgb(67, 40, 24);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed {\n"
                                            "    border-radius: 15px;\n"
                                            "    background-color: rgb(175, 138, 81);\n"
                                            "    color: rgb(67, 40, 24);\n"
                                            "}\n"
                                            "\n"
                                            "")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(235, 260, 130, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
                                           "    border-radius: 15px;\n"
                                           "    background-color: rgb(255, 230, 167);\n"
                                           "    color: rgb(67, 40, 24);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    border-radius: 15px;\n"
                                           "    background-color: rgb(187, 148, 87);\n"
                                           "    color: rgb(67, 40, 24);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "    border-radius: 15px;\n"
                                           "    background-color: rgb(175, 138, 81);\n"
                                           "    color: rgb(67, 40, 24);\n"
                                           "}\n"
                                           "\n"
                                           "")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(380, 260, 130, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setStyleSheet("QPushButton {\n"
                                            "    border-radius: 15px;\n"
                                            "    background-color: rgb(255, 230, 167);\n"
                                            "    color: rgb(67, 40, 24);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    border-radius: 15px;\n"
                                            "    background-color: rgb(187, 148, 87);\n"
                                            "    color: rgb(67, 40, 24);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed {\n"
                                            "    border-radius: 15px;\n"
                                            "    background-color: rgb(175, 138, 81);\n"
                                            "    color: rgb(67, 40, 24);\n"
                                            "}\n"
                                            "\n"
                                            "")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 230, 167);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 30, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 230, 167);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 30, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 230, 167);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.spinBox_hours = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_hours.setGeometry(QtCore.QRect(100, 70, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_hours.setFont(font)
        self.spinBox_hours.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_hours.setStyleSheet("border-radius: 15px;\n"
                                         "background-color: rgb(255, 230, 167);\n"
                                         "color: rgb(67, 40, 24);\n"
                                         "")
        self.spinBox_hours.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_hours.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_hours.setCorrectionMode(
            QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_hours.setMaximum(99)
        self.spinBox_hours.setDisplayIntegerBase(10)
        self.spinBox_hours.setObjectName("spinBox_hours")
        self.spinBox_minutes = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_minutes.setGeometry(QtCore.QRect(240, 70, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_minutes.setFont(font)
        self.spinBox_minutes.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_minutes.setStyleSheet("border-radius: 15px;\n"
                                           "background-color: rgb(255, 230, 167);\n"
                                           "color: rgb(67, 40, 24);\n"
                                           "")
        self.spinBox_minutes.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_minutes.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_minutes.setCorrectionMode(
            QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_minutes.setMaximum(59)
        self.spinBox_minutes.setDisplayIntegerBase(10)
        self.spinBox_minutes.setObjectName("spinBox_minutes")
        self.spinBox_seconds = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_seconds.setGeometry(QtCore.QRect(380, 70, 120, 120))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.spinBox_seconds.setFont(font)
        self.spinBox_seconds.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_seconds.setStyleSheet("border-radius: 15px;\n"
                                           "background-color: rgb(255, 230, 167);\n"
                                           "color: rgb(67, 40, 24);\n"
                                           "")
        self.spinBox_seconds.setWrapping(False)
        self.spinBox_seconds.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_seconds.setReadOnly(False)
        self.spinBox_seconds.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_seconds.setAccelerated(False)
        self.spinBox_seconds.setCorrectionMode(
            QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_seconds.setKeyboardTracking(True)
        self.spinBox_seconds.setPrefix("")
        self.spinBox_seconds.setMinimum(0)
        self.spinBox_seconds.setMaximum(59)
        self.spinBox_seconds.setProperty("value", 0)
        self.spinBox_seconds.setDisplayIntegerBase(10)
        self.spinBox_seconds.setObjectName("spinBox_seconds")
        self.comboBox_music = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_music.setGeometry(QtCore.QRect(450, 370, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_music.setFont(font)
        self.comboBox_music.setStyleSheet("border-radius: 15px;\n"
                                          "background-color: rgb(255, 230, 167);\n"
                                          "color: rgb(67, 40, 24);\n"
                                          "")
        self.comboBox_music.setEditable(False)
        self.comboBox_music.setObjectName("comboBox_music")
        self.comboBox_music.addItem("")
        self.comboBox_music.addItem("")
        self.comboBox_music.addItem("")
        self.comboBox_music.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.functions()

        # self.timer = QTimer(self)
        # self.timer.timeout.connect(self.showTime)
        # self.timer.setInterval(1000)  # 1 sec
        # self.time = 0

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timer"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "HOURS"))
        self.label_2.setText(_translate("MainWindow", "MINUTES"))
        self.label_3.setText(_translate("MainWindow", "SECONDS"))
        self.comboBox_music.setCurrentText(_translate("MainWindow", "1"))
        self.comboBox_music.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_music.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_music.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_music.setItemText(3, _translate("MainWindow", "4"))

    def functions(self):
        self.pushButton_start.clicked.connect(self.push_start)
        self.pushButton_stop.clicked.connect(self.push_stop)
        self.pushButton_reset.clicked.connect(self.push_reset)
        # self.pushButton_stop.clicked.connect(lambda: self.write_number(self.pushButton_stop.text()))
        # self.pushButton_reset.clicked.connect(lambda: self.write_number(self.pushButton_reset.text()))
        self.comboBox_music.currentTextChanged.connect(self.set_music)

    # def showTime(self):
    #     self.lcd.display(self.time)
    #     self.time -= 1  # !!!
    #     if self.time < 0:
    #         self.timer.stop()
    #         self.time = 0

    def push_start(self):
        hours = self.spinBox_hours.text()
        minutes = self.spinBox_minutes.text()
        seconds = self.spinBox_seconds.text()
        # self.timer.start()
        pass

    def push_stop(self):
        # останавливаем время
        pass

    def push_reset(self):
        self.spinBox_hours.setValue(0)
        self.spinBox_minutes.setValue(0)
        self.spinBox_seconds.setValue(0)

    def set_music(self):
        print(self.comboBox_music.currentText())


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
